version: "3"
services:
  vacalmu-server:
   image: vacalmu-server
   container_name: vacalmu-server
   ports:
      - "5000:5000"
  vacalmu-client:
    image: vacalmu-client
    container_name: vacalmu-client
    stdin_open: true
    ports:
      - "80:3000"
  